### ISSUE TITLE
Could not load file or assembly Octokit, Version=0.23.0.0

### ISSUE THREAD

**Issue by dario-l** [AntoineGa/Seq.App.Teams#13]
Hi,
I just installed Seq.App.Github package but when I want to send event to the github the error occurs. :(

```
System.IO.FileNotFoundException: Could not load file or assembly 'Octokit, Version=0.23.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

File name: 'Octokit, Version=0.23.0.0, Culture=neutral, PublicKeyToken=null'
   at SeqApps.GitHub.GitHubIssueReactor.CreateIssue(Event`1 evt)
   at SeqApps.GitHub.GitHubIssueReactor.On(Event`1 evt)
```

**Comment by nblumhardt** [comment]
Hi @dario-l - I think you've mistakenly posted this to the wrong repo (this is where the MS Teams app is developed).

The GitHub app is at: https://github.com/aliozgur/SeqApps

HTH!

**Comment by dario-l** [comment]
Ups. Thanks. Sorry. 😃
